# config.yaml

# DATA, DATASET
base_data_path: "../../data"
dataset:

# INPUT
num_pkts: 20
fields: ['PL', 'IAT', 'DIR', 'WIN', 'FLG', 'TTL']
all_fields: ['PL', 'IAT', 'DIR', 'WIN', 'FLG', 'TTL']
is_flat: False
pad_value_dir: 0.5
pad_value: -1
train_test_split: 0.7
train_val_split: 0.9

# EXPERIMENT
seed: 0
log_dir: "../results"
ml_appr: "random_forest"

# DL TRAINING
lr: 0.0001
lr_strat: 'none'
max_epochs: 100
min_epochs: 1

# RANDOM FOREST
rf_criterion: 'gini'
rf_n_estimators: 100
rf_max_depth:

# XGB
xgb_n_estimators: 100
xgb_max_depth: 3
xgb_eval_metric: 'mlogloss'

# KNN
knn_n_neighbors: 5
knn_weights: 'uniform'
knn_p: 2
knn_metric: 'minkowski'