# config.yaml

# DATA, DATASET
base_data_path: "../../data"
src-dataset:
trg-dataset:

# INPUT
num_pkts: 20
fields: ['PL', 'IAT', 'DIR', 'WIN', 'FLG', 'TTL']
all_fields: ['PL', 'IAT', 'DIR', 'WIN', 'FLG', 'TTL']
is_flat: False
pad_value_dir: 0.5
pad_value: -1
train_test_split: 0.7
train_val_split: 0.9

# EXPERIMENT
seed: 0
gpu: False
deterministic: True
log_dir: "../results"
n_task: 1
skip_t1:
approach:
k:

# DL TRAINING
lr: 0.0001
max_epochs: 100
min_epochs: 1

# LR SCHEDULER
lr_strat: 'none'
sch_monitor: 'loss'
lrop_mode: 'min'
lrop_factor: 0.1
lrop_patience: 5
cawr_t0: 10
cawr_t_mult: 1
cawr_eta_min: 1e-5

# EARLY STOPPING
es_monitor: 'loss'
es_mode: 'min'
es_patience: 10
es_min_delta: 0

# MODEL CHECKPOINT
mc_monitor: 'loss'
mc_mode: 'min'

# DATALOADER
batch_size: 64
num_workers: 0
pin_memory: True

# DL NETWORK
network: 'lopez17cnn'
weights_path:
net_scale: 1
num_classes: 0

# DL BASELINE
adaptation_strat: '' 

# RFS
alpha: 0.5
gamma: 0.5
is_distill:
kd_t: 1
tacher_path:

# RANDOM FOREST
rf_criterion: 'gini'
rf_n_estimators: 100
rf_max_depth:

# XGB
xgb_n_estimators: 100
xgb_max_depth: 3
xgb_eval_metric: 'mlogloss'

# KNN
knn_n_neighbors: 5
knn_weights: 'uniform'
knn_p: 2
knn_metric: 'minkowski'